#!/usr/bin/env bash
# Script that copy an element to a server using scp command

if [[ $# -eq 4 ]]
then
    file=$1; ip=$2; user=$3; key=$4
    scp -o StrictHostKeyChecking=no -i "$key" "$file" "$user"@"$ip":
else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
