#!/usr/bin/env bash
# Configure server nginx
apt-get update
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;
    rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}" > /etc/nginx/sites-enabled/default
service nginx restart
