#!/usr/bin/env bash
# Configures an Nginx server

apt-get update
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new="_;\n\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/_;/$new/" /etc/nginx/sites-available/default
service nginx restart
