#!/usr/bin/env bash
# Configure server nginx
apt-get update
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
#new_string = "listen [::]:80 default_server;\nrewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
#file="/etc/nginx/sites-enabled/default"
#sed -e s/"listen [::]:80 default_server;"/${new_string}"/g $file
service nginx restart
