#!/usr/bin/env bash
# Configures an Nginx server
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
new="_;\n\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/_;/$new/" /etc/nginx/sites-available/default
new2="permanent;\n\nerror_page    404 \/404.html;"
sed -i "s/permanent;/$new2/"
service nginx start
