#!/usr/bin/env bash
# Installs and configure server with Nginx:

apt-get update
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    add_header X-Served-By $HOSTNAME;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
