#!/usr/bin/env bash
# Script to fix nginx server to run in port 80
new="listen 80 default_server;"
sed -i "s/listen 8080 default_server;/$new/" /etc/nginx/sites-available/default
sed -i "s/listen 8080 default_server;/$new/" /etc/nginx/sites-enabled/default
service nginx restart