#!/usr/bin/env bash
#Script with infinity bucle
tmp_file="/var/run/holbertonscript.pid"
echo $$ > $tmp_file
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"' SIGTERM
trap 'rm $tmp_file; exit' SIGTERM SIGQUIT
while "true"
do
    echo "To infinity and beyond"
    sleep 2
done
