#!/usr/bin/env bash
#Prints numbers from 1 to 10 
x=1

while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    elif [ $x -eq 8 ]
    then
        echo "good luck"
    else
        echo "Holberton school"
    fi
    ((x++))
done
