#!/usr/bin/env bash
#Prints numbers from 1 to 20 and more
#bad luck from China -> if is 4th repeat
#bad luck from Japan -> if is 9th repeat
#bad luck from Italy -> if is 17th repeat

x=1
while [ $x -le 20 ]
do
    echo "$x"
    case $x in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    esac
    ((x++))
done
