#!/usr/bin/env bash
#Print the numbers style Clock from 0..59 and 0..12

hours=0
minutes=0

while [ $hours -le 12 ]
do
    echo "Hour: $hours"
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        (( minutes++ ))
    done
    (( hours++ ))
    minutes=0
done
