#!/usr/bin/env bash
#Search if a file exist, is empty, regular file and more
filename="holbertonschool"

if [ -e $filename ]
then
    echo "$filename file exists"
    if [ -s $filename ]
    then
        echo "$filename file is not empty"
    else
        echo "$filename file is empty"
    fi
    if [ -f $filename ]
    then
        echo "$filename is a regular file"
    fi
else
    echo "$filename file does not exist"
fi

