#!/usr/bin/env bash
#Edit the file /etc/hosts                                                                                    
cp /etc/hosts ~/hosts_new                                                 
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts_new
echo "8.8.8.8 facebook.com" >> ~/hosts_new
cat ~/hosts_new > /etc/hosts