#!/usr/bin/env bash
# Run a nginx server using nginx user
sed "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
