#!/usr/bin/env bash
# Run a nginx server using nginx user
sed "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
echo "user	nginx" >> /etc/nginx/nginx.conf
sudo -u nginx service nginx start
